package zendesk

// DO NOT EDIT
// This file is generated by script/create_locale_types.rb
//
// 64 locales are supported

const (
	// LocaleENUS English
	LocaleENUS = iota
	// LocaleES Spanish - español
	LocaleES
	// LocaleDE German - Deutsch
	LocaleDE
	// LocaleZHTW Traditional Chinese - 繁體中文
	LocaleZHTW
	// LocaleZHCN Simplified Chinese - 简体中文
	LocaleZHCN
	// LocalePL Polish - polski
	LocalePL
	// LocaleFR French - français
	LocaleFR
	// LocalePTBR Brazilian Portuguese - português (Brasil)
	LocalePTBR
	// LocaleIT Italian - italiano
	LocaleIT
	// LocaleRO Romanian - română
	LocaleRO
	// LocaleIS Icelandic - íslenska
	LocaleIS
	// LocaleVI Vietnamese - Tiếng Việt
	LocaleVI
	// LocaleRU Russian - русский
	LocaleRU
	// LocaleHE Hebrew - עברית
	LocaleHE
	// LocaleNO Norwegian - norsk
	LocaleNO
	// LocaleFIL Filipino
	LocaleFIL
	// LocaleAR Arabic - العربية
	LocaleAR
	// LocaleJA Japanese - 日本語
	LocaleJA
	// LocaleKO Korean - 한국어
	LocaleKO
	// LocaleSL Slovenian - slovenščina
	LocaleSL
	// LocaleHR Croatian - hrvatski
	LocaleHR
	// LocaleID Indonesian - Indonesia
	LocaleID
	// LocaleCS Czech - čeština
	LocaleCS
	// LocaleTH Thai - ไทย
	LocaleTH
	// LocaleFI Finnish - suomi
	LocaleFI
	// LocaleTR Turkish - Türkçe
	LocaleTR
	// LocaleSV Swedish - svenska
	LocaleSV
	// LocaleEL Greek - Ελληνικά
	LocaleEL
	// LocaleBG Bulgarian - български
	LocaleBG
	// LocaleET Estonian - eesti
	LocaleET
	// LocaleDA Danish - dansk
	LocaleDA
	// LocaleSK Slovak - slovenčina
	LocaleSK
	// LocaleNL Dutch - Nederlands
	LocaleNL
	// LocaleHU Hungarian - magyar
	LocaleHU
	// LocalePT Portuguese - português
	LocalePT
	// LocaleFA Persian - فارسی
	LocaleFA
	// LocaleCA Catalan - català
	LocaleCA
	// LocaleLT Lithuanian - lietuvių
	LocaleLT
	// LocaleLV Latvian - latviešu
	LocaleLV
	// LocaleSR Serbian - српски
	LocaleSR
	// LocaleUK Ukrainian - українська
	LocaleUK
	// LocaleENGB British English
	LocaleENGB
	// LocaleENCA Canadian English
	LocaleENCA
	// LocaleESES European Spanish - español de España
	LocaleESES
	// LocaleFRCA Canadian French - français canadien
	LocaleFRCA
	// LocaleES419 Latin American Spanish - español latinoamericano
	LocaleES419
	// LocaleENAU Australian English
	LocaleENAU
	// LocaleENIN English (India)
	LocaleENIN
	// LocaleENIE English (Ireland)
	LocaleENIE
	// LocaleENSG English (Singapore)
	LocaleENSG
	// LocaleENNZ English (New Zealand)
	LocaleENNZ
	// LocaleENZA English (South Africa)
	LocaleENZA
	// LocaleFRBE French (Belgium) - français (Belgique)
	LocaleFRBE
	// LocaleFRCH Swiss French - français suisse
	LocaleFRCH
	// LocaleNLBE Flemish - Nederlands (België)
	LocaleNLBE
	// LocaleDEAT Austrian German - Österreichisches Deutsch
	LocaleDEAT
	// LocaleDECH Swiss High German - Schweizer Hochdeutsch
	LocaleDECH
	// LocaleSRME Serbian (Montenegro) - srpski (Crna Gora)
	LocaleSRME
	// LocaleHI Hindi - हिन्दी
	LocaleHI
	// LocaleMS Malay - Bahasa Melayu
	LocaleMS
	// LocaleENBE English (Belgium)
	LocaleENBE
	// LocaleESMX Mexican Spanish - español de México
	LocaleESMX
	// LocaleFRFR French (France) - français (France)
	LocaleFRFR
	// LocaleENPH English (Philippines)
	LocaleENPH
)

var localeTypeText = map[int]string{
	// LocaleENUS English
	LocaleENUS: "en-US",
	// LocaleES Spanish - español
	LocaleES: "es",
	// LocaleDE German - Deutsch
	LocaleDE: "de",
	// LocaleZHTW Traditional Chinese - 繁體中文
	LocaleZHTW: "zh-tw",
	// LocaleZHCN Simplified Chinese - 简体中文
	LocaleZHCN: "zh-cn",
	// LocalePL Polish - polski
	LocalePL: "pl",
	// LocaleFR French - français
	LocaleFR: "fr",
	// LocalePTBR Brazilian Portuguese - português (Brasil)
	LocalePTBR: "pt-br",
	// LocaleIT Italian - italiano
	LocaleIT: "it",
	// LocaleRO Romanian - română
	LocaleRO: "ro",
	// LocaleIS Icelandic - íslenska
	LocaleIS: "is",
	// LocaleVI Vietnamese - Tiếng Việt
	LocaleVI: "vi",
	// LocaleRU Russian - русский
	LocaleRU: "ru",
	// LocaleHE Hebrew - עברית
	LocaleHE: "he",
	// LocaleNO Norwegian - norsk
	LocaleNO: "no",
	// LocaleFIL Filipino
	LocaleFIL: "fil",
	// LocaleAR Arabic - العربية
	LocaleAR: "ar",
	// LocaleJA Japanese - 日本語
	LocaleJA: "ja",
	// LocaleKO Korean - 한국어
	LocaleKO: "ko",
	// LocaleSL Slovenian - slovenščina
	LocaleSL: "sl",
	// LocaleHR Croatian - hrvatski
	LocaleHR: "hr",
	// LocaleID Indonesian - Indonesia
	LocaleID: "id",
	// LocaleCS Czech - čeština
	LocaleCS: "cs",
	// LocaleTH Thai - ไทย
	LocaleTH: "th",
	// LocaleFI Finnish - suomi
	LocaleFI: "fi",
	// LocaleTR Turkish - Türkçe
	LocaleTR: "tr",
	// LocaleSV Swedish - svenska
	LocaleSV: "sv",
	// LocaleEL Greek - Ελληνικά
	LocaleEL: "el",
	// LocaleBG Bulgarian - български
	LocaleBG: "bg",
	// LocaleET Estonian - eesti
	LocaleET: "et",
	// LocaleDA Danish - dansk
	LocaleDA: "da",
	// LocaleSK Slovak - slovenčina
	LocaleSK: "sk",
	// LocaleNL Dutch - Nederlands
	LocaleNL: "nl",
	// LocaleHU Hungarian - magyar
	LocaleHU: "hu",
	// LocalePT Portuguese - português
	LocalePT: "pt",
	// LocaleFA Persian - فارسی
	LocaleFA: "fa",
	// LocaleCA Catalan - català
	LocaleCA: "ca",
	// LocaleLT Lithuanian - lietuvių
	LocaleLT: "lt",
	// LocaleLV Latvian - latviešu
	LocaleLV: "lv",
	// LocaleSR Serbian - српски
	LocaleSR: "sr",
	// LocaleUK Ukrainian - українська
	LocaleUK: "uk",
	// LocaleENGB British English
	LocaleENGB: "en-gb",
	// LocaleENCA Canadian English
	LocaleENCA: "en-ca",
	// LocaleESES European Spanish - español de España
	LocaleESES: "es-es",
	// LocaleFRCA Canadian French - français canadien
	LocaleFRCA: "fr-ca",
	// LocaleES419 Latin American Spanish - español latinoamericano
	LocaleES419: "es-419",
	// LocaleENAU Australian English
	LocaleENAU: "en-au",
	// LocaleENIN English (India)
	LocaleENIN: "en-in",
	// LocaleENIE English (Ireland)
	LocaleENIE: "en-ie",
	// LocaleENSG English (Singapore)
	LocaleENSG: "en-sg",
	// LocaleENNZ English (New Zealand)
	LocaleENNZ: "en-nz",
	// LocaleENZA English (South Africa)
	LocaleENZA: "en-za",
	// LocaleFRBE French (Belgium) - français (Belgique)
	LocaleFRBE: "fr-be",
	// LocaleFRCH Swiss French - français suisse
	LocaleFRCH: "fr-ch",
	// LocaleNLBE Flemish - Nederlands (België)
	LocaleNLBE: "nl-be",
	// LocaleDEAT Austrian German - Österreichisches Deutsch
	LocaleDEAT: "de-at",
	// LocaleDECH Swiss High German - Schweizer Hochdeutsch
	LocaleDECH: "de-ch",
	// LocaleSRME Serbian (Montenegro) - srpski (Crna Gora)
	LocaleSRME: "sr-me",
	// LocaleHI Hindi - हिन्दी
	LocaleHI: "hi",
	// LocaleMS Malay - Bahasa Melayu
	LocaleMS: "ms",
	// LocaleENBE English (Belgium)
	LocaleENBE: "en-be",
	// LocaleESMX Mexican Spanish - español de México
	LocaleESMX: "es-mx",
	// LocaleFRFR French (France) - français (France)
	LocaleFRFR: "fr-fr",
	// LocaleENPH English (Philippines)
	LocaleENPH: "en-ph",
}

// LocaleTypeText returns locale type text
func LocaleTypeText(loc int) string {
	return localeTypeText[loc]
}
